name = "Sky FABRICation 2 Light"
author = "MSandro"
version = "1.0.1d"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf684e8cc3ce95194edb05171741f98d59fd1862acd7ea75b7b0a0dd7b613476"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
