name = "Sky FABRICation 2 Light"
author = "MSandro"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40540783fee6a4cda857c8df09078829bdb8a568e1b12ea0d046b03d4253b232"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
