name = "Sky FABRICation 2 Light"
author = "MSandro"
version = "1.0.1a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05fa5fd5b4c185ea6bc195d02148fd976b08d99968d214fdfbbdcfb7e7d37fc6"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
