name = "Sky FABRICation 2 Light"
author = "MSandro"
version = "1.0.1b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e25f8780a52dd578e1624545907db3bd9f164e57a1f13c96621d94ecc5cea459"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
