name = "Sky FABRICation 2 Light"
author = "MSandro"
version = "1.0.1a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a36820c31709bb3771b7911ca88d1cb38e23976dde0bd289a440ad624ac1a32a"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
