name = "Cloth Config API (Fabric)"
filename = "cloth-config-5.3.58-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/134/cloth-config-5.3.58-fabric.jar"
hash-format = "murmur2"
hash = "3591598947"

[update]
[update.curseforge]
file-id = 3641134
project-id = 319057
