name = "Paradise Lost - The Aether Reborn"
filename = "paradise-lost-1.6.5.3+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/306/paradise-lost-1.6.5.3+1.17.1.jar"
hash-format = "murmur2"
hash = "115989056"

[update]
[update.curseforge]
file-id = 3651306
project-id = 418680
